# Generated by Django 2.2.6 on 2019-12-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge1', models.CharField(max_length=100)),
                ('edge2', models.CharField(max_length=100)),
                ('edge3', models.CharField(max_length=100)),
                ('edge4', models.CharField(max_length=100)),
                ('edge5', models.CharField(max_length=100)),
                ('edge6', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
